"""add is_active to users

Revision ID: 22cba7ee99c1
Revises: 3c9ab84ca44c
Create Date: 2026-01-14 14:30:34.734583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cba7ee99c1'
down_revision = '3c9ab84ca44c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("1"))
        )

    # (optional but recommended) remove the default after existing rows are populated
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("is_active", server_default=None)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
