"""add availability and scheduling

Revision ID: 3c9ab84ca44c
Revises: bdfdd8f49f94
Create Date: 2026-01-13 22:36:48.330384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect



# revision identifiers, used by Alembic.
revision = '3c9ab84ca44c'
down_revision = 'bdfdd8f49f94'
branch_labels = None
depends_on = None

def _column_exists(conn, table_name, column_name):
    rows = conn.execute(sa.text(f"PRAGMA table_info({table_name})")).fetchall()
    return any(r[1] == column_name for r in rows)

def _table_exists(conn, table_name: str) -> bool:
    return inspect(conn).has_table(table_name)

def upgrade():
    conn = op.get_bind()

    # 1) Create availability table only if it doesn't exist
    if not _table_exists(conn, "availability"):
        op.create_table(
            "availability",
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
            sa.Column("start_time", sa.DateTime(), nullable=False),
            sa.Column("end_time", sa.DateTime(), nullable=False),
            sa.Column("timezone", sa.String(length=64), nullable=False, server_default="America/Denver"),
            sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("1")),
            sa.Column("created_at", sa.DateTime(), nullable=True),
        )
        op.create_index("ix_availability_user_id", "availability", ["user_id"])

    # 2) Add columns to session_requests only if missing
    if not _column_exists(conn, "session_requests", "scheduled_start"):
        op.add_column("session_requests", sa.Column("scheduled_start", sa.DateTime(), nullable=True))

    if not _column_exists(conn, "session_requests", "scheduled_end"):
        op.add_column("session_requests", sa.Column("scheduled_end", sa.DateTime(), nullable=True))

    if not _column_exists(conn, "session_requests", "timezone"):
        op.add_column("session_requests", sa.Column("timezone", sa.String(length=64), nullable=True))

    if not _column_exists(conn, "session_requests", "schedule_status"):
        op.add_column(
            "session_requests",
            sa.Column("schedule_status", sa.String(length=20), nullable=False, server_default="none"),
        )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_requests', schema=None) as batch_op:
        batch_op.drop_column('schedule_status')
        batch_op.drop_column('timezone')
        batch_op.drop_column('scheduled_end')
        batch_op.drop_column('scheduled_start')

    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availability_user_id'))

    op.drop_table('availability')
    # ### end Alembic commands ###
