"""add reviews

Revision ID: 72ce4e9dc02c
Revises: 9e9a264e7845
Create Date: 2026-01-15 11:21:01.172531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ce4e9dc02c'
down_revision = '9e9a264e7845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_request_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_request_id'], ['session_requests.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_request_id', 'from_user_id', name='uq_review_one_per_user_per_session')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_from_user_id'), ['from_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_session_request_id'), ['session_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_to_user_id'), ['to_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_to_user_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_session_request_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_from_user_id'))

    op.drop_table('reviews')
    # ### end Alembic commands ###
