"""add session requests

Revision ID: d2e4ea4a5a83
Revises: d8903bbc11da
Create Date: 2026-01-13 21:58:51.772482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e4ea4a5a83'
down_revision = 'd8903bbc11da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_requests_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_requests_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_requests_skill_id'), ['skill_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_requests_skill_id'))
        batch_op.drop_index(batch_op.f('ix_session_requests_requester_id'))
        batch_op.drop_index(batch_op.f('ix_session_requests_provider_id'))

    op.drop_table('session_requests')
    # ### end Alembic commands ###
